import { useCallback } from "react";
import { useAppStore } from "../stores/appStore";
import { analyzeImage, ApiError } from "../services/api";
import { deriveAnalysis } from "../utils/derive";
import type { ChatMessage, UploadedImage } from "../types";

/** Upload + analysis. One request, not two: `POST /analyze` takes the file and returns the
 *  fused findings, so the old upload-then-analyze pair had no counterpart on the backend. */
export function useAnalysis() {
  const {
    setUploadedImage,
    setAnalysis,
    setSessionId,
    setIsAnalyzing,
    setErrorMessage,
    setChatMessages,
    isAnalyzing,
    errorMessage,
  } = useAppStore();

  const handleUpload = useCallback(
    async (file: File) => {
      setErrorMessage(null);

      // Show the X-ray immediately, before the round trip. Inference takes under a second
      // but the file read is instant, and a panel that stays empty during analysis reads as
      // a failed upload.
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => reject(reader.error);
        reader.readAsDataURL(file);
      });

      const preview: UploadedImage = {
        name: file.name,
        size: file.size,
        type: file.type,
        dataUrl,
      };
      setUploadedImage(preview);
      setIsAnalyzing(true);

      try {
        // Pass the current session id so a second X-ray lands in the SAME consultation:
        // the chat history survives and the agent is re-grounded on the new findings.
        const sessionId = useAppStore.getState().sessionId;
        const res = await analyzeImage(file, sessionId);

        const view = deriveAnalysis(res);
        setSessionId(res.session_id);
        setAnalysis(view);

        // Announce the result in the transcript. Written locally rather than by asking
        // Claude to summarise: the findings are already known, and spending a full agent
        // turn to restate them would cost tokens for nothing.
        const counts = view.counts;
        const note: ChatMessage = {
          id: "sys-" + Date.now(),
          role: "system",
          text:
            `Analysis complete — ${counts.detected} teeth detected, ` +
            `${res.findings.length} finding${res.findings.length === 1 ? "" : "s"}. ` +
            `Ask me anything about them.`,
          timestamp: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }),
        };
        setChatMessages((prev) => [...prev, note]);
      } catch (err) {
        const msg =
          err instanceof ApiError
            ? err.message
            : "Unable to process the uploaded image. Use a JPG or PNG panoramic and retry.";
        setErrorMessage(msg);
        // Leave the preview on screen: the dentist can see which file failed, and clearing
        // it makes a decode error look like the upload never happened.
        setAnalysis(null);
      } finally {
        setIsAnalyzing(false);
      }
    },
    [setAnalysis, setChatMessages, setErrorMessage, setIsAnalyzing, setSessionId, setUploadedImage]
  );

  /** Download the findings as JSON. Built in the browser from what is already in the store —
   *  the backend has no /report endpoint, and adding one would only re-serialise data the
   *  client is holding. */
  const exportReport = useCallback(() => {
    const { analysis, uploadedImage } = useAppStore.getState();
    if (!analysis) return;

    const payload = {
      generated_at: new Date().toISOString(),
      source_image: uploadedImage?.name ?? null,
      session_id: analysis.sessionId,
      image_size: { width: analysis.imageWidth, height: analysis.imageHeight },
      counts: analysis.counts,
      teeth: analysis.teeth.filter((t) => t.status !== "Undetected"),
      unattributed_findings: analysis.unattributed,
      restorations: analysis.restorations,
      ambiguous_fdi: analysis.ambiguousFdi,
      summary: analysis.summary,
      disclaimer:
        "Generated by an academic demonstration system. AI findings require clinical " +
        "confirmation and are not a diagnosis.",
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `dentalvision-report-${analysis.sessionId.slice(0, 8)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  return { handleUpload, exportReport, isAnalyzing, errorMessage };
}
